github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
#image: jupyter/pyspark-notebook
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    init: gp open README.md && git clone https://github.com/confluentinc/cp-all-in-one && git clone https://github.com/sknop/kafka-docker-composer && gp sync-done setup
    command: exit
  - name: Create Compose
    init: gp sync-await setup
    command: cd kafka-docker-composer && python kafka_docker_composer.py -z 3 -b 3 -C 2 -s 2 --control-center -p -r 7.5.0 --docker-compose-file cp7-zk.yaml && python kafka_docker_composer.py -c 3 -b 3 -C 2 -s 2 --control-center -p -r 7.5.0 --docker-compose-file cp7-kraft.yaml && exit
    openMode: split-right
  

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 8888
#     onOpen: open-preview
vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-python.python
